Merged hand evaluator project to peanut
Severity Code Description Project File Line Suppression State
Error CS1729 'TokClassDef' does not contain a constructor that takes 3
arguments peanut
C:\Users\Roy\Documents\git\peanut\peanutB74436810\peanut\peanut\PocketQueryParser\Runtime\genbase0.cs
105 Active

Still needs to be fixed